name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - run: nix flake check
      - run: nix build
      - run: cp -r --no-preserve=mode,ownership result/public/ public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: https://www.nevi.dev
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
