name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: nevivurn-nevi-dev
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix flake check
      - run: nix build
      - run: cp -r --no-preserve=mode,ownership result/public/ public/

      - uses: actions/upload-pages-artifact@v1
        with:
          path: public/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v2
        id: deploy-pages
