name: Github Pages

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26

      - run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - run: nix flake check
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - run: nix build
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - run: cp -r --no-preserve=mode,ownership result/public/ public/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
        id: deploy-pages
